// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bohwhykdtlepssygofew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvaHdoeWtkdGxlcHNzeWdvZmV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NDg0NDIsImV4cCI6MjA1NzAyNDQ0Mn0.YSZCNvivA2z76-P17--oxW93aKPjqUfhhqLevWoHj0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);